### PR TITLE
Update controllers and configuration file

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Ditto.

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
https://cyberbotics.github.io/webots-animation-template/update-controllers/tutorial_1.html

but the following page still needs an update:
https://cyberbotics.github.io/webots-animation-template/update-controllers/#tutorial_1

**Comment by stefaniapedrazzi** [comment]
Thank you!


> but the following page still needs an update:
> https://cyberbotics.github.io/webots-animation-template/update-controllers/#tutorial_1

For this issue, it is the `webots-animation-action` directly that should be updated, is it correct?

**Comment by lukicdarkoo** [comment]
> For this issue, it is the `webots-animation-action` directly that should be updated, is it correct?

Yes, we are working on it

**Review by lukicdarkoo — APPROVED** [review]
Thank you

**Pull request merged**
